spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:diplomacy_test}
    username: ${DB_USER:diplomacy}
    password: ${DB_PASSWORD:diplomacy}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:diplomacy_test}
    user: ${DB_USER:diplomacy}
    password: ${DB_PASSWORD:diplomacy}
