spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/diplomacy_test
    username: diplomacy
    password: diplomacy

  flyway:
    url: jdbc:postgresql://localhost:5432/diplomacy_test
    user: diplomacy
    password: diplomacy
